### PR TITLE
Refactored perms for report/watchlist info/broadcasts

### PR DESCRIPTION
**Pull request by DAHPr0gram3r**
Changed PlayerPermissions.PlayersManagement to PlayerPermissions.AdminChat for report/watchlist info/broadcasts as some staff may not have playermanagement perms

Noticed the issue after I shamefully ripped your broadcast code for an internal adminchat syncing plugin after 2 hours of ripping my hair out trying to get it to work. Then after having one of our tmods mess about with playermanagement they lost those perms resulting in them not being able to see broadcasts from the admin chat sync and also from reports being logged even when they have the preferences set correctly.

### CODE REVIEW

**Comment by ced777ric** [comment]
Did you intend to also change the ReportHandling stuff to the AdminChat permission?

**Comment by DAHPr0gram3r** [comment]
yes i may have missed some as i just searched for PlayerPermissions.PlayersManagement in the code base as that was the perm check i knew was the issue on our server so i may have missed some although it may be an idea to change it to the pluginapi/exiled permissions system as then it can be completely seperate from base game perms as they can be rather broad. this is however completely up to you as im not familiar with your coding style or the code base it self, as such i tried to keep the edits as minimal as possible to not disturb your coding style and reduce possible bugs, due to the references used in the project i have been unable to build it to test so it will need a final check but if you are able to build it for me i can test it for you.

**Comment by ced777ric** [comment]
The pullrequest would change the behaviour of the Reports menu in RA to work with adminchat permissions, although it could be a better idea to use the ban perms for it, as people with those perms can actually handle reports/deal with watchlist entries.

**Comment by DAHPr0gram3r** [comment]
I've set all the perms for claiming, ingnoring and completing reports to PlayerPermissions.BanningUpToDay, and the perms to view the various player icons, view unclaimed and handled reports to  PlayerPermissions.AdminChat. Those perms make the most sense to me as then if someone on the watchlist come on or if reports come in the staff can still keep an eye on anyone reported until someone who is able to handle the report is able to come on. If you would prefer it a different way I can change it for you.

**Pull request merged**
