### PR TITLE
RA modification patches to transpilers

### PR DESCRIPTION
**Pull request by Axwabo**
Harmony prefixes are an easy way to modify a method but may prevent others from further modifying it.

Converted the following patches to transpilers:
- RaPlayerListPatch
- RaPlayerPatch
- RaPlayerAuthPatch

This enables other developers to patch the methods.

### CODE REVIEW

**Comment by moddedmcplayer** [comment]
just so you know you're gonna be the one maintaining them or they'll just become prefixes again next time this changes lmao xd

**Comment by ced777ric** [comment]
And this has all been tested?

**Comment by Axwabo** [comment]
Can confirm that all modified features work:

image
image

**Review by ced777ric — CHANGES_REQUESTED** [review]
Resolve conflicts, idk how the transpilers do their thing so im not gonna touch it for now

**Comment by Misaka-ZeroTwo** [comment]
> just so you know you're gonna be the one maintaining them or they'll just become prefixes again next time this changes lmao xd

get good and learn how it works XD

**Comment by moddedmcplayer** [comment]
> > just so you know you're gonna be the one maintaining them or they'll just become prefixes again next time this changes lmao xd
> 
> get good and learn how it works XD

no

**Pull request closed without merging**
